# Generated by Django 3.2.9 on 2021-11-14 06:50

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='score',
            field=models.IntegerField(default=1, validators=[django.core.validators.MinValueValidator(5), django.core.validators.MaxValueValidator(20)], verbose_name='Question Score'),
            preserve_default=False,
        ),
    ]
